package OOPSinJAVA.ExceptionHandling;

public class Main {
    public static void main(String[] args ) throws InterruptedException{
       new Error1().show();

        // new Demo_Error2().printNumber();
    }
}
